### ISSUE TITLE
version number broken

### ISSUE THREAD

**Issue by core-code** [zkokaja/Brewlet#25]
i've downloaded what is supposed to be version 1.5, but it identifies itself as version 1.0

both the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist are broken
<img width="730" alt="Screenshot 2021-01-28 at 22 39 18" src="https://user-images.githubusercontent.com/1261954/106202157-cd87b880-61b9-11eb-9b3c-72a628cdc3a9.png">

**Comment by zkokaja** [comment]
Ah thanks for pointing this out! I'll fix it in the next release.

**Comment by core-code** [comment]
awesome, thanks :)

**Comment by zkokaja** [comment]
Closing this due as we are now a version 1.6

**Comment by core-code** [comment]
there is now a version 1.6, yes but it still has broken version numbers so please reopen this:
<img width="256" alt="Screenshot 2022-04-11 at 19 08 47" src="https://user-images.githubusercontent.com/1261954/162793395-c58b473e-b71b-4bf1-8fa0-458ae2d4f3c5.png">

should be 1.6 not 1.5

**Comment by zkokaja** [comment]
You're right, please check #30 for fix on this

**Comment by core-code** [comment]
thanks i can fully confirm that the user visible version number (CFBundleShortVersionString) is now correct.

whats still missing (but probably not really important) is that the *actual* version number (CFBundleVersion) is still at "1" so if you have multiple versions installed, macOS won't know which one the newest is.
