### ISSUE TITLE
Stuck in dark mode icon

### ISSUE THREAD

**Issue by verstratenbram** [zkokaja/Brewlet#39]
My brewlet icon is always in dark mode (blue-ish) even though my MacBook is set to light mode.
Toggling the appearance doesn't fix it. Neither does restarting the app.
I'm on macOS Sonoma 14.2.1 (M1 chip)

**Comment by zkokaja** [comment]
Hi, the blue icon indicates that there are formulae or casks ready to be upgraded, it is not the icon for dark mode. On my system, when everything is up-to-date, the icon is white in both light mode and dark mode.

You can run `brew outdated` in a terminal to see what can be updated, and whether or not those show up in Brewlet depends on your preferences, specifically, "Include dependency updates".

**Comment by verstratenbram** [comment]
Maybe I'm going crazy but I'm sure the icon used to be yellow (like beer) on light mode and blue on dark mode when updates are available 🤯

**Comment by zkokaja** [comment]
Oh, you're right, I do have a yellow icon for light mode and a blue icon for dark mode, but for me it always shows blue regardless of the mode (i think the system takes over the color tint when i set the image `isTemplate = true`). I'll take a look..

But, i'm still not sure why your icon is _stuck_ on it, even if there are no packages to be upgraded?

**Comment by verstratenbram** [comment]
I believe there is a misunderstanding. When there are no packages to be upgraded the icon is fine:
![image](https://github.com/zkokaja/Brewlet/assets/29309992/87a57153-676f-4745-9856-203d4adfdd24)

It's like you say when there are upgrades available, the icon is blue on light mode instead of yellow:
![image](https://github.com/zkokaja/Brewlet/assets/29309992/97a3058a-ccf4-4243-a460-0c3578494ff8)
![image](https://github.com/zkokaja/Brewlet/assets/29309992/ebb537fb-74fe-498e-a5ca-dd5869421208)

Not a big issue but I just wanted to report it 🙂

**Comment by zkokaja** [comment]
Ah ok thanks for clarifying! I'll take a look at what happened to the yellow icon 🤔

**Comment by zkokaja** [comment]
So it seems to me that the icon behavior depends more so on the wallpaper you choose than solely light/dark mode. Previously, I had a static, black wallpaper that always showed icons in their light mode (white icons, blue Brewlet). But, when I switched to a dynamic wallpaper like Monterey (which changes based on light/dark mode), my menu bar items started to change as well (and Brewlet started to show the yellow icon again). Could this be a similar issue on your end?

**Comment by verstratenbram** [comment]
It seems you are correct. The same thing happens on my end. In that case everything is working as expected 🙂
