### ISSUE TITLE
New Feature: Upgrade all and/or automatic upgrade

### ISSUE THREAD

**Issue by blcarson** [zkokaja/Brewlet#4]
I don't have a need to monitor or control which package is being upgraded or when, so adding either of these features (with supporting notifications) would be great.

**Comment by zkokaja** [comment]
That's a great idea, thanks! I'm adding this feature for the next release.

**Comment by zkokaja** [comment]
This feature has been added to release [v1.4](https://github.com/zkokaja/Brewlet/releases/tag/v1.4)
