### ISSUE TITLE
Upgrade button can be clicked many times

### ISSUE THREAD

**Issue by jonjaques** [zkokaja/Brewlet#5]
- Installed app
- had packages out of date, so I clicked "Upgrade"
- app is doing stuff in the background, but no indication of progress 🤷 

edit: the keg icon is "filling", but see title.
ps: good stuff, thank you!

**Comment by zkokaja** [comment]
Agreed, the upgrade button should be disabled when it's running in the background. Will fix, thanks!

**Comment by zkokaja** [comment]
This fix has been implemented in release [v1.4](https://github.com/zkokaja/Brewlet/releases/tag/v1.4)
