### ISSUE TITLE
New Feature: Start or stop brew services

### ISSUE THREAD

**Issue by marvelph** [zkokaja/Brewlet#8]
I need to do a reboot after upgrading the daemon package, so it would be great if I could do it in Brewlet.

**Comment by marvelph** [comment]
Yes.
I use it when I notice that more than one daemon has been updated at a time.

**Comment by zkokaja** [comment]
Functionality added in 006e52ebb29275a4661d7102461d76e9985073d1, and will be included in the next release.

**Comment by zkokaja** [comment]
[v1.5](https://github.com/zkokaja/Brewlet/releases) released now supports this functionality. Please open an issue if you run into problems with it since this is not a feature I use.
